Catalog of Things
michaelamponsah/project-catalog pull request #43
Opened 2023-03-23 14:47 UTC by michaelamponsah

### Hello ☺️, 

#### In this PR, the following requirements have been implemented:
 
- [x] Implemented `Book`  and `Label` requirements
- [x] Implemented `MusicAlbum`  and `Genre` requirements
- [x]  Implemented `Games`  and `Author` requirements
- [x] Added tests for all methods implemented
- [x] Preserved data in `.json`  files
- [x] Implemented a UI for user interactions with the application

### Below are sample screenshots of the interface

  
![cat-1](https://user-images.githubusercontent.com/42746317/227240658-943d9492-eb56-4309-a1b9-e8381a8437f1.PNG)
![cat-2](https://user-images.githubusercontent.com/42746317/227240667-4488ab4a-4a3f-4650-addc-6a3ea2c2faf7.PNG)
![cat-3](https://user-images.githubusercontent.com/42746317/227240671-10042e6a-71b0-42f1-b2c8-5eed05bc08f3.PNG)

2023-03-23 16:37 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @michaelamponsah, @willy836, @oguntayomicheal :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow (For Development)
✔️ Following GitHub Flow (For External Review)
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 16:37 UTC, HAMMAS-SALEEM commented on classes/file_processor.rb
> +
- [ ] It would be great if those methods which are saving data into files should be used when user quits the app because sometimes we work with transactions and we need all the transactions to complete at once not a single one so to achieve that we always save our data into files when our app quits. I saw that you have used this method for games. When you input data then it won't be saved directly into your game.json file but when you quit your application then your app will save the data into the game.json file :+1: Kindly do the same thing to book, albums, genres, labels, author to make consistency in your application behavior :+1:

2023-03-24 14:07 UTC, OyePriscilla requested changes
Hi @michaelamponsah, @oguntayomicheal and @willy836 👍 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Add unit tests ✔️ 
Store data in files ✔️ 
Build interactive console apps ✔️ 
Made most of the required changes ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 14:45 UTC, michaelamponsah commented on database/schema.sql
> +    id  INT,
We must have missed that!
Thanks!

2023-03-24 14:45 UTC, michaelamponsah commented on MIT.md
> +## Copyright 2023, Catalog Team
Great tips, we'd make the corrections.
Thanks

2023-03-24 14:51 UTC, elisha2kyakpo1 approved these changes
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did a great job implementing the changes requested by previous reviewers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 15:06 UTC, merged